import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Bell,
  BookOpen,
  Calendar,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  ClipboardList,
  Clock,
  Copy,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Image,
  Info,
  KeyRound,
  LayoutDashboard,
  LineChart,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Mic,
  MonitorUp,
  Music,
  Paperclip,
  Pause,
  PhoneOff,
  Play,
  Plus,
  RefreshCw,
  RotateCw,
  Save,
  Search,
  Settings,
  Share2,
  Shield,
  Smartphone,
  Sword,
  Target,
  Trash,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Video,
  X,
  Zap,
} from 'lucide'

type IconNode = readonly (readonly [string, Record<string, string | number | undefined>])[]

const ICONS: Record<string, IconNode> = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  plus: Plus,
  bookOpen: BookOpen,
  users: Users,
  clipboardList: ClipboardList,
  checkCircle: CircleCheck,
  xCircle: CircleX,
  alertTriangle: AlertTriangle,
  info: Info,
  x: X,
  layoutDashboard: LayoutDashboard,
  calendar: Calendar,
  bell: Bell,
  mail: Mail,
  mic: Mic,
  monitorUp: MonitorUp,
  logOut: LogOut,
  menu: Menu,
  settings: Settings,
  user: User,
  sword: Sword,
  trophy: Trophy,
  dollarSign: DollarSign,
  scrollText: FileText,
  target: Target,
  shield: Shield,
  search: Search,
  filter: Filter,
  upload: Upload,
  download: Download,
  edit: Edit,
  trash: Trash,
  play: Play,
  externalLink: ExternalLink,
  helpCircle: CircleQuestionMark,
  paperclip: Paperclip,
  image: Image,
  clock: Clock,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  mapPin: MapPin,
  eye: Eye,
  pause: Pause,
  phoneOff: PhoneOff,
  share2: Share2,
  music: Music,
  save: Save,
  fileText: FileText,
  zap: Zap,
  copy: Copy,
  rotate: RotateCw,
  smartphone: Smartphone,
  video: Video,
  trendingUp: TrendingUp,
  award: Award,
  keyRound: KeyRound,
  lineChart: LineChart,
  refreshCw: RefreshCw,
  check: Check,
  camera: Camera,
}

function escapeAttribute(value: string | number): string {
  return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char))
}

function kebabCase(value: string): string {
  return value.replace(/[A-Z]/g, char => `-${char.toLowerCase()}`)
}

export function Icon(name: string, size = 18): string {
  const nodes = ICONS[name] || CircleQuestionMark
  const body = nodes.map(([tag, attributes]) => {
    const attrs = Object.entries(attributes)
      .map(([key, value]) => ` ${kebabCase(key)}="${escapeAttribute(value ?? '')}"`)
      .join('')
    return `<${tag}${attrs}></${tag}>`
  }).join('')

  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`
}
